services:
  - type: web
    name: hojaverde-backend
    env: python
    plan: starter  # Cambiar a 'standard' para producción
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: hojaverde-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
    healthCheckPath: /health
    domains:
      - hojaverde-api.onrender.com
    
  - type: postgres
    name: hojaverde-db
    plan: starter
    databaseName: hojaverde
    user: hojaverde
    region: oregon
    postgresMajorVersion: 15