"""Agregar tablas de usuarios y autenticación

Revision ID: 6378c3ef28d2
Revises: 535128a25e1e
Create Date: 2025-06-03 06:18:03.892683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6378c3ef28d2'
down_revision: Union[str, None] = '535128a25e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'SUSPENDIDO', 'BLOQUEADO', name='estadousuarioenum'), nullable=False),
    sa.Column('rol', sa.Enum('SUPER_ADMIN', 'ADMIN', 'SUPERVISOR', 'RECURSOS_HUMANOS', 'USUARIO', name='rolenum'), nullable=False),
    sa.Column('permisos_adicionales', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=True),
    sa.Column('configuraciones', sa.Text(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('password_cambiado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_activos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id')
    )
    op.create_index('idx_usuario_email_activo', 'usuarios', ['email', 'is_active'], unique=False)
    op.create_index('idx_usuario_empleado', 'usuarios', ['empleado_id'], unique=False)
    op.create_index('idx_usuario_rol_estado', 'usuarios', ['rol', 'estado'], unique=False)
    op.create_index('idx_usuario_ultimo_acceso', 'usuarios', ['ultimo_acceso'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('historial_passwords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historial_usuario_fecha', 'historial_passwords', ['usuario_id', 'fecha_cambio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_historial_usuario_fecha', table_name='historial_passwords')
    op.drop_table('historial_passwords')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index('idx_usuario_ultimo_acceso', table_name='usuarios')
    op.drop_index('idx_usuario_rol_estado', table_name='usuarios')
    op.drop_index('idx_usuario_empleado', table_name='usuarios')
    op.drop_index('idx_usuario_email_activo', table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
